=== luqmannurf/tugas_webservice2/tugas_webservice2luqman/meja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="distribusi">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jenis"/>
                <xs:element ref="jumlah"/>
                <xs:element ref="harga"/>
                <xs:element ref="distributor"/>
                <xs:element ref="manajer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jenis" type="xs:string"/>
    <xs:element name="jumlah" type="xs:integer"/>
    <xs:element name="harga" type="xs:integer"/>
    <xs:element name="distributor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:NCName"/>
    <xs:element name="kode" type="xs:integer"/>
    <xs:element name="manajer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="nomor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:NCName"/>
    <xs:element name="nomor" type="xs:integer"/>
</xs:schema>

=== luqmannurf/tugas_webservice2/tugas_webservice2luqman/meja.xml
<?xml version="1.0" encoding="UTF-8"?>
<distribusi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="meja.xsd">
    <barang>
        <jenis>meja kopi</jenis>
        <jumlah>10</jumlah>
        <harga>25000</harga>
        <distributor>
            <pt>columbus</pt>
            <kode>1154054</kode>
        </distributor>
        <manajer>
            <nama>luqman</nama>
            <nomor>1</nomor>
        </manajer>
    </barang>
    <barang>
        <jenis>meja makan</jenis>
        <jumlah>5</jumlah>
        <harga>250000</harga>
       <distributor>
            <pt>borma</pt>
            <kode>11540544</kode>
        </distributor>
        <manajer>
            <nama>luqmen</nama>
            <nomor>11</nomor>
        </manajer>
    </barang>
</distribusi>
